name: colors_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# dart run build_runner watch --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter

  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.8

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  solid_lints: ^0.1.5

flutter:

  uses-material-design: true